backend:
  name: github
  repo: tallestthomas/tomrasmussen
  branch: master

media_folder: "content/img"

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: "content/"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: "string" }
      - { name: date, label: Date, widget: "date" }
      - { name: category, label: Category, widget: "string" }
      - { name: tabs, label: Tags, widget: "string" }
      - { name: body, label: Body, widget: "markdown" }
